project:
  type: website
  output-dir: docs

website:
  title: "Josh Rosen Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - current_projects.qmd
      - cv.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



