project:
  type: website
  output-dir: docs

website:
  title: "Romantically Involved with Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: current_projects.qmd
        text: Current Projects
      - href: even_more.qmd
        text: Other 'Projects'
      - href: blog_formatting.qmd
        text: Blog

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



