project:
  type: website
  output-dir: docs

website:
  title: "Romantically Involved with Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - current_projects.qmd
      - cv.qmd
      - even_more.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



